#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
TOTAL_MINUTES=35

# Secrets land beside the app that reads them, which is also where a local run
# picks them up — so a second run of this wizard offers what the first captured.
ENV_FILE="apps/api/.env"

banner "auto-learn — deploy"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Before you start" 2
say "Render builds from GitHub, not from this directory."
say "Anything unpushed will not be in the deploy."
printf '\n'

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  warn "not a git repository — run this from inside the repo"
  exit 1
fi

# Every path below — ENV_FILE especially — is relative to the repo root, so
# the wizard works from any subdirectory.
cd "$(git rev-parse --show-toplevel)"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
step "On branch: $BRANCH"

if [[ -n "$(git status --porcelain)" ]]; then
  warn "you have uncommitted changes; they will not deploy"
fi

if git rev-parse "@{u}" >/dev/null 2>&1; then
  AHEAD=$(git rev-list --count "@{u}..HEAD")
  if [[ "$AHEAD" != "0" ]]; then
    warn "$AHEAD commit(s) not pushed — push before deploying"
  else
    step "Up to date with the remote."
  fi
else
  warn "no upstream branch set for $BRANCH"
fi

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  step "gh is authenticated — secrets and variables can be set for you."
else
  warn "gh is not authenticated; this wizard will tell you what to set by hand"
fi

confirm "Continue?" || { warn "stopped — nothing has been changed"; exit 0; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "OpenAI — key and a spend cap" 5
say "Both model calls run through this key. There is no login in front of"
say "them, so the cap matters as much as the key."
open_url "https://platform.openai.com/api-keys"
step "Create a secret key (or reuse one), then copy it."
ask_secret OPENAI_API_KEY "Paste the OpenAI key:"
write_env OPENAI_API_KEY "$OPENAI_API_KEY"
# The evals workflow reads this one from CI.
set_secret OPENAI_API_KEY "$OPENAI_API_KEY"
printf '\n'
say "Now the cap. The per-IP limits bound one caller, not a distributed one —"
say "the rate limit stops a script, the cap stops everything else."
open_url "https://platform.openai.com/settings/organization/limits"
step "Set a monthly budget you would not mind losing."
pause "Set the cap?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "ElevenLabs — voice (optional)" 4
say "Skip this and dictation and spoken pronunciation refuse; everything else"
say "works, including the dictionary's own recordings. The API says which are"
say "missing at boot."
printf '\n'
if confirm "Set up voice now?"; then
  open_url "https://elevenlabs.io/app/settings/api-keys"
  ask_secret ELEVENLABS_API_KEY "Paste the ElevenLabs key:"
  write_env ELEVENLABS_API_KEY "$ELEVENLABS_API_KEY"

  say "The voice id is account-scoped — take it from your own My Voices rather"
  say "than reusing one from a tutorial. The shared Default voices are being"
  say "withdrawn, so a borrowed id stops working on a date nobody chose."
  open_url "https://elevenlabs.io/app/voice-library"
  step "Open a voice you own → copy its Voice ID."
  ask ELEVENLABS_VOICE_ID "Paste the voice id:"
  write_env ELEVENLABS_VOICE_ID "$ELEVENLABS_VOICE_ID"
else
  SKIPPED+=("ElevenLabs voice — dictation and spoken pronunciation will refuse")
  ELEVENLABS_API_KEY=""
  ELEVENLABS_VOICE_ID=""
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Render — apply the blueprint" 6
say "render.yaml describes both services: the API and a keyvalue store for"
say "sessions. Render reads it; you do not create them by hand."
open_url "https://dashboard.render.com/blueprints"
step "New Blueprint Instance → connect this repository → Apply."
printf '\n'
say "It will create:"
step "auto-learn-api        (web service, starter — free instances sleep, and"
say "                       a sleeping instance zeroes the counters you deployed for)"
step "auto-learn-sessions   (keyvalue — REDIS_URL is wired in for you)"
printf '\n'
say "The first build takes a few minutes. It runs pnpm install, which builds"
say "the WordNet index the dictionary needs — if that step is skipped, every"
say "card fails."
pause "Blueprint applied and building?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Render — the values the file cannot carry" 4
say "Three secrets stay out of git, so the blueprint leaves them empty."
say "WEB_ORIGIN comes later — the Vercel URL does not exist yet."
open_url "https://dashboard.render.com/"
step "auto-learn-api → Environment."
printf '\n'
say "Set:"
step "OPENAI_API_KEY        $(printf '%s' "${OPENAI_API_KEY:0:7}")…"
if [[ -n "${ELEVENLABS_API_KEY:-}" ]]; then
  step "ELEVENLABS_API_KEY    $(printf '%s' "${ELEVENLABS_API_KEY:0:7}")…"
  step "ELEVENLABS_VOICE_ID   ${ELEVENLABS_VOICE_ID}"
fi
printf '\n'
say "They are in $ENV_FILE if you need to copy them again."
pause "Saved, and the service is redeploying?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Render — take the URL and check it answers" 3
say "Wait for the deploy to go live, then copy the service URL from the top of"
say "its page. It looks like https://auto-learn-api.onrender.com"
ask API_URL "Paste the API URL (no trailing slash):"
API_URL="${API_URL%/}"
write_env API_URL "$API_URL"
printf '\n'

HEALTH=$(curl -fsS --max-time 20 "$API_URL/health" 2>/dev/null || true)
if [[ "$HEALTH" == *'"ok"'* ]]; then
  step "$API_URL/health answered ok."
else
  warn "no healthy answer yet from $API_URL/health"
  say "The first deploy can take a few minutes. Check the Render logs if it"
  say "stays quiet — a failed install shows up here first."
  confirm "Carry on anyway?" || {
    warn "stopped. Re-run this wizard once the deploy is live — the values"
    warn "already captured are in $ENV_FILE and will be offered back."
    exit 0
  }
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Vercel — the web app" 6
say "Two settings decide whether this works, and both are easy to miss."
open_url "https://vercel.com/new"
step "Import this repository."
printf '\n'
say "1. Root Directory: leave it at the repository root, NOT apps/web."
say "   The build compiles packages/shared first and cannot reach above the"
say "   root directory."
printf '\n'
say "2. Environment variable:"
step "   NEXT_PUBLIC_API_URL = $API_URL"
printf '\n'
say "That one is inlined at build time, not read at runtime — which is why the"
say "API had to exist first. Changing it later means a rebuild, not a restart."
pause "Deployed?"

ask WEB_ORIGIN "Paste the Vercel URL (no trailing slash):"
WEB_ORIGIN="${WEB_ORIGIN%/}"
write_env WEB_ORIGIN "$WEB_ORIGIN"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Render — let the browser in" 3
say "The API allows exactly one origin. Until it knows the Vercel URL, every"
say "request from the browser fails CORS — which looks identical to the API"
say "being down."
open_url "https://dashboard.render.com/"
step "auto-learn-api → Environment → set WEB_ORIGIN = $WEB_ORIGIN"
pause "Saved, and the service has restarted?"
printf '\n'

ALLOWED=$(curl -fsSI --max-time 20 -H "Origin: $WEB_ORIGIN" "$API_URL/health" 2>/dev/null \
  | tr -d '\r' | grep -i '^access-control-allow-origin:' || true)
if [[ -n "$ALLOWED" ]]; then
  step "CORS is answering: ${ALLOWED}"
else
  warn "no access-control-allow-origin header for $WEB_ORIGIN"
  say "Check WEB_ORIGIN matches the Vercel URL exactly — scheme included, no"
  say "trailing slash — and that the restart finished."
fi

say "Note: Vercel gives every preview deployment its own URL, so previews are"
say "blocked against this API. Tolerable, or widen the check knowingly."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Telemetry — hourly snapshots" 2
say "The workflow reads GET /telemetry every hour and appends it to"
say "telemetry/snapshots.jsonl. It needs the API's address."
say "A variable, not a secret: secrets are masked in logs, which makes a"
say "failure unreadable, and this is only a URL."
set_var API_URL "$API_URL"
printf '\n'

SNAPSHOT=$(curl -fsS --max-time 20 "$API_URL/telemetry" 2>/dev/null || true)
if [[ -n "$SNAPSHOT" ]]; then
  step "Telemetry is answering."
  say "Counters reset on restart; each snapshot carries 'since', so a reset"
  say "reads as a new window rather than numbers going backwards."
else
  warn "no answer from $API_URL/telemetry"
fi
printf '\n'
say "That endpoint has no authentication. There is no user data in it, but it"
say "is your product metrics on an open URL — worth a shared secret before you"
say "tell anyone the address."

finish

printf '  %sOpen it:%s %s\n' "$BOLD" "$RESET" "$WEB_ORIGIN"
printf '  %sWatch:%s   cardsDelivered against proposals, and editsDropped as a share\n' "$BOLD" "$RESET"
printf '           of proposals — see docs/deploy.md for why that last one\n'
printf '           qualifies the others.\n\n'
